Merging Base MessageMaster and State Machine
albertaloop/T_SWE_2019_2020 pull request #36
Opened 2022-01-11 05:21 UTC by itsfeas

This pull request aims to merge the various classes, as well as the state machine code to master.

Currently to-do with this iteration of the code:

-Supply actual parameter values to StateMachine. If there is a need for functions to model bamocar input, please supply them. 

-Perform Unit testing of FlexCAN message FIFO setup to ensure that:

	-The code stops reading messages when there are no messages left to be read (motor_controller/main.cpp)

	-The FIFO buffer has been set up correctly, such that it can store messages until they can be read

-Perform Unit testing of BamocarInterface to ensure that unit conversions have been correctly supplied

-Unit Test StateMachine position tracking. StateMachine should stop the run after 100m. This relies on a successful nav module. 

-Move the MessageMaster and prebuilt classes/headers to a better location

2022-01-11 05:27 UTC, itsfeas commented
Do you guys mind taking a look at the motor_controller folder? 

@OkTerrific you might want to look at the MessageMaster class

2022-01-12 04:24 UTC, mbardwell requested changes
A few general comments:
1. awesome work. Thanks for contributing!
2. we want to keep everything in a single `platformio.ini` file. That way, we can write libraries that are easily includable in a number of executables (ie. we will just need to add `#include "bleh.h"` to .cpp files). For this PR, Here, state machine, gpstest, etc... are all compiled using separate .ini files. I recommend merging them
3. Ideally, GPSTest would be added in a separate PR
4. There is existing code in the repo that does what the Sending/Recipient tests do. I recommend removing them from this PR

2022-01-12 04:24 UTC, mbardwell commented on StateMachine/src/main.cpp
> +#include "ChRt.h"
If threading proves to be error-prone we might remove it and try again in the future if we see the need. Feel free to leave it in for now

2022-01-12 04:24 UTC, mbardwell commented on StateMachine/src/MessageMaster.h
> +enum BamocarCanID
Suggestion: have all possible CanID's in one `enum`

2022-01-12 04:24 UTC, mbardwell commented on StateMachine/src/MessageMaster.h
> +    MessageMaster(FlexCAN_T4<CAN0, RX_SIZE_256, TX_SIZE_16> &PrimaryBus, FlexCAN_T4<CAN1, RX_SIZE_256, TX_SIZE_16> &BamocarBus);
again, for a more general `FlexCAN_T4`-based constructor, see [this](https://github.com/albertaloop/T_SWE_2019_2020/pull/31/files#diff-111717fa100e44ba15a71abc3bd81bcf27edabc806e998096c9bb65e7b06ec5fR55)

2022-03-23 02:51 UTC, closed without merging